### ISSUE TITLE
getty.exe died in 2024

### ISSUE THREAD

**Issue by fvbatistoni** [m-rots/getty#8]
Since 2024 I can not use getty.exe anymore. Could you update the code???? Is it possible?
![erro-getty](https://github.com/m-rots/getty/assets/30464918/cc6996bb-1707-47c5-836a-6a8187fb8cc4)

**Comment by m-rots** [comment]
It appears that gettyimages has (finally) implemented presigned URLs. Previously, the query string of the URL only included the watermark (w) and size (s). But now it also includes a signature.

Old: `?s=2048x2048&w=5`
New: `?s=2048x2048&w=gi&k=20&c=okVHhRLiqHWp1gyzTKqFhkpOugJeae3IYvIWChc9AFw=`

The way getty worked is by merging two pictures together, each with the watermark in a different position. In other words, it downloaded both watermark version 5 and 125 and cropped out different parts of the image. Now that gettyimages signs URLs server-side, one cannot simply change the watermark anymore, as the resulting signature would be different. This signature is the result of signing the contents of the URL with a key which is private to gettyimages. Bruteforcing this key is close to impossible, which is why I believe similar projects, such as ZeonDownloader, have disappeared over night. I highly suspect that gettyimages hasn’t implemented this change to combat projects such as getty and ZeonDownloader, but to protect its IP from being included in the training sets of text-to-image systems such as DALL-E 3 without a license agreement (also see The New York Times vs OpenAI lawsuit).

As I haven’t used getty myself in years, I unfortunately have no time to explore a workaround. But hopefully this background information serves as a sufficient explanation for why this project, as well as other similar projects, stopped working.
